language: ruby
rvm:
  - "2.2.2"
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec
addons:
  code-climate:
     repo-token: 3c8e54c8e5da85c1712a36df9c4e2158e0835d8f77ee08302927cf9ce0f95e3b
before_install:
  - mysql -e "create database IF NOT EXISTS test;" -u root -p root
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - mysql -e 'create database amurabuzz_test;'
  - bundle exec rake db:migrate RAILS_ENV=test