# Use the README file as a reference to customize settings.

Relationship:
  fields:
    default: follower_id, followed_id
    form: follower_id, followed_id
  relationships: 
  application: Application
