# Use the README file as a reference to customize settings.

User:
  fields:
    default: user_name, name, dob, bio, email, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, confirmed_at, confirmation_sent_at, unconfirmed_email, failed_attempts, unlock_token, locked_at, provider, uid
    form: user_name, name, dob, bio, email, encrypted_password
  relationships: activities, tweets, evaluations, relationships, following, reverse_relationships, followers
  application: Application
